export const products = [
  {
    id: 1,
    name: "Bánh mì gạo Organic 500g",
    unit: "cái",
    total: 100,
    categoryId: 9,
    price: 5000,
    category: "Bánh mỳ",
  },
  {
    id: 2,
    name: "Sữa tươi nguyên chất hộp 1 lít",
    unit: "hộp",
    total: 50,
    categoryId: 6,
    price: 15000,
    category: "Đồ uống",
  },
  {
    id: 3,
    name: "Thịt bò sạch 100% không chất bảo quản 1kg",
    unit: "kg",
    total: 30,
    categoryId: 3,
    price: 150000,
    category: "Thịt",
  },
  {
    id: 4,
    name: "Bánh quy socola hạt lúa mạch 300g",
    unit: "gói",
    total: 80,
    categoryId: 5,
    price: 20000,
    category: "Đồ ăn vặt và kẹo",
  },
  {
    id: 5,
    name: "Cà phê hòa tan cao cấp Arabica 500g",
    unit: "hộp",
    total: 40,
    categoryId: 6,
    price: 25000,
    category: "Đồ uống",
  },
];

export const categories = [
  {
    id: 1,
    name: "Trái cây & Rau cải",
    description:
      "Bao gồm các loại trái cây và rau cải tươi sạch, giàu dinh dưỡng và thích hợp cho chế biến thực phẩm.",
  },
  {
    id: 2,
    name: "Trứng",
    description:
      "Chứa các sản phẩm như sữa tươi, sữa bột, trứng gà, trứng vịt, đảm bảo cung cấp nguồn protein và canxi cần thiết.",
  },
  {
    id: 3,
    name: "Thịt & Gà",
    description:
      "Bao gồm các loại thịt và gia cầm tươi sạch, được chế biến và đóng gói cẩn thận để đảm bảo chất lượng và an toàn.",
  },
  {
    id: 4,
    name: "Ngũ cốc & Mì ống",
    description:
      "Chứa các sản phẩm như gạo, mì ống, mì gói, ngũ cốc, là nguồn cung cấp năng lượng và carbohydrate cần thiết cho cơ thể.",
  },
  {
    id: 5,
    name: "Đồ ăn vặt & Kẹo",
    description:
      "Bao gồm các sản phẩm như bánh quy, kẹo, snack, được chế biến và đóng gói để đem lại trải nghiệm vui vẻ và ngon miệng.",
  },
  {
    id: 6,
    name: "Đồ uống",
    description:
      "Chứa các loại đồ uống như nước ngọt, nước ép, trà, cà phê, đảm bảo cung cấp sự tươi mới và ngon miệng.",
  },
  {
    id: 7,
    name: "Thực phẩm đông lạnh",
    description:
      "Bao gồm các sản phẩm thực phẩm đã chế biến sẵn, chỉ cần đun nấu hoặc làm nóng trước khi thưởng thức.",
  },
  {
    id: 8,
    name: "Gia vị & Sốt",
    description:
      "Chứa các sản phẩm như gia vị, sốt, gia vị cơ bản và phức tạp, giúp tăng thêm hương vị cho các món ăn.",
  },
  {
    id: 9,
    name: "Bánh mỳ",
    description:
      "Chứa các loại bánh mỳ tươi ngon, sẵn sàng phục vụ cho bữa ăn hàng ngày hoặc làm nguyên liệu cho các món ăn sáng tạo.",
  },
  {
    id: 10,
    name: "Đồ hộp",
    description:
      "Bao gồm các sản phẩm đóng hộp như thực phẩm đóng hộp, nước ngọt đóng hộp, đảm bảo dễ dàng sử dụng và bảo quản.",
  },
];

export const suppliers = [
  {
    id: 1,
    name: "Công ty TNHH Vật liệu xây dựng ABC",
    address: "123 Đường Nguyễn Văn A, Quận 1, Thành phố Hồ Chí Minh",
    email: "info@abcconstruction.com",
    phone: "0901234567",
    tax: "123456789",
    website: "http://www.abcconstruction.com",
  },
  {
    id: 2,
    name: "Cửa hàng Thực phẩm XYZ",
    address: "456 Đường Lê Văn B, Quận 2, Thành phố Hồ Chí Minh",
    email: "sales@xyzfoodstore.com",
    phone: "0912345678",
    tax: "987654321",
    website: "http://www.xyzfoodstore.com",
  },
  {
    id: 3,
    name: "Nhà phân phối Điện máy QWE",
    address: "789 Đường Trần Hưng Đạo, Quận 3, Thành phố Hồ Chí Minh",
    email: "contact@qwemachinery.com",
    phone: "0923456789",
    tax: "246813579",
  },
  {
    id: 4,
    name: "Công ty Công nghệ DEF",
    address: "1011 Đường Nguyễn Thị Minh Khai, Quận 4, Thành phố Hồ Chí Minh",
    email: "info@deftech.com",
    phone: "0934567890",
    tax: "369258147",
    website: "http://www.deftech.com",
  },
  {
    id: 5,
    name: "Cửa hàng Thời trang GHI",
    address: "1213 Đường Trần Phú, Quận 5, Thành phố Hồ Chí Minh",
    email: "sales@ghifashion.com",
    phone: "0945678901",
    tax: "147258369",
    website: "http://www.ghifashion.com",
  },
];
export const members = [
  {
    id: "0987654321",
    name: "Nguyễn Văn A",
    gender: "Nam",
    dob: "15-05-1990",
    createdDate: 1654200000000,
    point: 5000,
  },
  {
    id: "0912345678",
    name: "Trần Thị B",
    gender: "Nữ",
    dob: "20-10-1985",
    createdDate: 1648000000000,
    point: 7000,
  },
  {
    id: "0976543210",
    name: "Lê Văn C",
    gender: "Nam",
    dob: "28-02-1995",
    createdDate: 1651000000000,
    point: 3000,
  },
  {
    id: "0965432109",
    name: "Phạm Thị D",
    gender: "Nữ",
    dob: "12-08-1988",
    createdDate: 1652000000,
    point: 4500,
  },
];

export const staffs = [
  {
    id: "NV001",
    name: "Nguyễn Văn A",
    phone: "0901234567",
    email: "nva@example.com",
    role: "admin",
    username: "nva",
    dob: "1990-05-15",
  },
  {
    id: "NV002",
    name: "Trần Thị B",
    phone: "0912345678",
    email: "ttb@example.com",
    role: "staff",
    username: "ttb",
    dob: "1985-10-20",
  },
  {
    id: "NV003",
    name: "Lê Văn C",
    phone: "0923456789",
    email: "lvc@example.com",
    role: "staff",
    username: "lvc",
    dob: "1995-02-28",
  },
  {
    id: "NV004",
    name: "Phạm Thị D",
    phone: "0934567890",
    email: "ptd@example.com",
    role: "staff",
    username: "ptd",
    dob: "1988-08-12",
  },
];


export const recommendProductFake = {
  error: false,
  responseTimestamp: "2024-12-24T03:30:11.710Z",
  statusCode: 200,
  data: [
    {
      id: 128,
      name: "Máy nướng bánh mì",
      unit: "cái",
      total: 0,
      price: 350000,
      categoryId: 10,
      saleTotal: 0,
    },
    {
      id: 65,
      name: "Bộ bát đĩa",
      unit: "set",
      total: 0,
      price: 150000,
      categoryId: 4,
      saleTotal: 0,
    },
    {
      id: 100,
      name: "Nước tẩy trang Garnier",
      unit: "chai",
      total: 0,
      price: 150000,
      categoryId: 7,
      saleTotal: 0,
    },
    {
      id: 105,
      name: "Túi nilon Hàn Quốc",
      unit: "gói",
      total: 0,
      price: 25000,
      categoryId: 8,
      saleTotal: 0,
    },
    {
      id: 108,
      name: "Bông tẩy trang",
      unit: "gói",
      total: 0,
      price: 50000,
      categoryId: 8,
      saleTotal: 0,
    },
    {
      id: 47,
      name: "Bánh quy cà phê",
      unit: "hộp",
      total: 0,
      price: 35000,
      categoryId: 2,
      saleTotal: 0,
    },
    {
      id: 16,
      name: "Dầu ăn Neptune",
      unit: "lít",
      total: 0,
      price: 45000,
      categoryId: 12,
      saleTotal: 0,
    },
    {
      id: 113,
      name: "Thức ăn cho chó Pedigree",
      unit: "gói",
      total: 0,
      price: 150000,
      categoryId: 9,
      saleTotal: 0,
    },
    {
      id: 15,
      name: "Bánh quy Oreo",
      unit: "gói",
      total: 0,
      price: 30000,
      categoryId: 2,
      saleTotal: 0,
    },
    {
      id: 20,
      name: "Nước ngọt Fanta",
      unit: "chai",
      total: 0,
      price: 12000,
      categoryId: 1,
      saleTotal: 0,
    },
    {
      id: 52,
      name: "Bánh crepe",
      unit: "chiếc",
      total: 0,
      price: 30000,
      categoryId: 2,
      saleTotal: 0,
    },
    {
      id: 148,
      name: "Muối tinh",
      unit: "kg",
      total: 70,
      price: 5000,
      categoryId: 12,
      saleTotal: 70,
    },
    {
      id: 25,
      name: "Nước trái cây ép táo",
      unit: "hộp",
      total: 0,
      price: 20000,
      categoryId: 1,
      saleTotal: 0,
    },
  ],
};